version: '3.7'

networks:
  backend:
    name: backend

services:

  redis:
    networks:
      - backend
    image: redis:6.2-alpine
    restart: always

  celery:
    networks:
      - backend
    build:
      context: ../src
      dockerfile: ./celery_/deployment/Dockerfile
    devices:
      - '/dev/ttyACM0:/dev/ttyACM0'
    depends_on:
      - redis
    volumes:
      - '../src/data:/data'

  api:
    networks:
      - backend
    build:
      context: ../src
      dockerfile: ./api/deployment/Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - celery

  ui:
    build:
      context: ../src
      dockerfile: ./ui/deployment/Dockerfile
    ports:
      - '3000:3000'

